"""init

Revision ID: fccf382feff7
Revises:
Create Date: 2025-08-12 23:27:12.347184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fccf382feff7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("title", name=op.f("uq_tasks_title")),
    )
    op.add_column("users", sa.Column("hashed_password", sa.String(length=100), nullable=False))
    op.add_column("users", sa.Column("role", sa.String(length=10), nullable=False))
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    op.create_unique_constraint(op.f("uq_users_username"), "users", ["username"])
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("users", "role")
    op.drop_column("users", "hashed_password")
    op.drop_table("tasks")
    # ### end Alembic commands ###
