"""adds relationship one-to-many user-tasks

Revision ID: f56beb965b19
Revises: fccf382feff7
Create Date: 2025-08-14 01:12:31.745496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56beb965b19'
down_revision: Union[str, Sequence[str], None] = 'fccf382feff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_tasks_user_id_users'), 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_user_id_users'), 'tasks', type_='foreignkey')
    # ### end Alembic commands ###
